spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShif=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: true
# Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  #Use this to befriend spring-boot-starter-actuator & springfox-boot-starter
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8081

flickr:
  apiKey: b311d0420737522313582895dd70b84d
  apiSecret: cdcca45c852b8772
  appKey: 72157720885630826-e94e1062269ad114
  appSecret: e4febf1eb02f894e